-- This file has been generated by Ion. Do not edit.
return {
    [0] = {
        ["type"] = "WRootWin",
        ["name"] = "WRootWin",
        ["managed"] = {
            [1] = {
                ["pseudomodal"] = true,
                ["type"] = "WGroupWS",
                ["name"] = "WIonWS",
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1366,
                    ["h"] = 768,
                },
                ["switchto"] = true,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WIonWS<1>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1366,
                            ["h"] = 768,
                        },
                        ["split_tree"] = {
                            ["tls"] = 571,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<4>",
                                    ["managed"] = {
                                        [1] = {
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW",
                                            ["hidden"] = true,
                                            ["geom"] = {
                                                ["y"] = 13,
                                                ["x"] = 0,
                                                ["w"] = 1366,
                                                ["h"] = 558,
                                            },
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["windowid"] = 6291464,
                                                    ["checkcode"] = 1,
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["y"] = 5,
                                                        ["x"] = 1,
                                                        ["w"] = 1364,
                                                        ["h"] = 548,
                                                    },
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["level"] = 0,
                                        },
                                        [2] = {
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW<3>",
                                            ["geom"] = {
                                                ["y"] = 13,
                                                ["x"] = 0,
                                                ["w"] = 1366,
                                                ["h"] = 558,
                                            },
                                            ["switchto"] = true,
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["windowid"] = 12582920,
                                                    ["checkcode"] = 2,
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["y"] = 5,
                                                        ["x"] = 1,
                                                        ["w"] = 1364,
                                                        ["h"] = 548,
                                                    },
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["level"] = 0,
                                        },
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 197,
                            ["br"] = {
                                ["tls"] = 683,
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<1>",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW<1>",
                                                ["geom"] = {
                                                    ["y"] = 13,
                                                    ["x"] = 0,
                                                    ["w"] = 683,
                                                    ["h"] = 184,
                                                },
                                                ["switchto"] = true,
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["bottom"] = true,
                                                        ["windowid"] = 8388616,
                                                        ["checkcode"] = 3,
                                                        ["sizepolicy"] = "full",
                                                        ["geom"] = {
                                                            ["y"] = 0,
                                                            ["x"] = 1,
                                                            ["w"] = 680,
                                                            ["h"] = 184,
                                                        },
                                                        ["level"] = 1,
                                                    },
                                                },
                                                ["level"] = 0,
                                            },
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["dir"] = "horizontal",
                                ["brs"] = 683,
                                ["br"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW<2>",
                                                ["geom"] = {
                                                    ["y"] = 13,
                                                    ["x"] = 0,
                                                    ["w"] = 683,
                                                    ["h"] = 184,
                                                },
                                                ["switchto"] = true,
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["bottom"] = true,
                                                        ["windowid"] = 10485768,
                                                        ["checkcode"] = 4,
                                                        ["sizepolicy"] = "full",
                                                        ["geom"] = {
                                                            ["y"] = 0,
                                                            ["x"] = 1,
                                                            ["w"] = 680,
                                                            ["h"] = 184,
                                                        },
                                                        ["level"] = 1,
                                                    },
                                                },
                                                ["level"] = 0,
                                            },
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [2] = {
                ["pseudomodal"] = true,
                ["type"] = "WGroupWS",
                ["name"] = "lol",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1366,
                    ["h"] = 768,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1366,
                            ["h"] = 768,
                        },
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["mode"] = 1,
                                ["type"] = "WFrame",
                                ["name"] = "WFrame<3>",
                                ["managed"] = {
                                    [1] = {
                                        ["type"] = "WGroupCW",
                                        ["name"] = "WGroupCW<4>",
                                        ["hidden"] = true,
                                        ["geom"] = {
                                            ["y"] = 13,
                                            ["x"] = 0,
                                            ["w"] = 1366,
                                            ["h"] = 755,
                                        },
                                        ["sizepolicy"] = "full",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WClientWin",
                                                ["bottom"] = true,
                                                ["windowid"] = 14680072,
                                                ["checkcode"] = 5,
                                                ["sizepolicy"] = "full",
                                                ["geom"] = {
                                                    ["y"] = 6,
                                                    ["x"] = 1,
                                                    ["w"] = 1364,
                                                    ["h"] = 743,
                                                },
                                                ["level"] = 1,
                                            },
                                        },
                                        ["level"] = 0,
                                    },
                                    [2] = {
                                        ["type"] = "WGroupCW",
                                        ["name"] = "WGroupCW<5>",
                                        ["geom"] = {
                                            ["y"] = 13,
                                            ["x"] = 0,
                                            ["w"] = 1366,
                                            ["h"] = 755,
                                        },
                                        ["switchto"] = true,
                                        ["sizepolicy"] = "full",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WClientWin",
                                                ["bottom"] = true,
                                                ["windowid"] = 16777251,
                                                ["checkcode"] = 6,
                                                ["sizepolicy"] = "full",
                                                ["geom"] = {
                                                    ["y"] = 0,
                                                    ["x"] = 0,
                                                    ["w"] = 1366,
                                                    ["h"] = 755,
                                                },
                                                ["level"] = 1,
                                            },
                                        },
                                        ["level"] = 0,
                                    },
                                },
                            },
                            ["type"] = "WSplitRegion",
                        },
                    },
                },
                ["level"] = 0,
            },
            [3] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "full_bounds",
                ["managed"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchpad*",
                ["pseudomodal"] = true,
                ["hidden"] = true,
                ["mode"] = 0,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1366,
                    ["h"] = 768,
                },
                ["level"] = 1024,
            },
        },
    },
}

